# Generated by Django 4.2.5 on 2023-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('google_maps_url', models.CharField(max_length=100)),
                ('conductor', models.CharField(default='', max_length=100)),
                ('assigned_to', models.CharField(default='', max_length=100)),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'OrganizationDetails',
            },
        ),
    ]
